image:
  - Visual Studio 2019
  - Ubuntu
  - macos

branches:
  except:
    - gh-pages

environment:
  SonarKey:
    secure: SM3ZT7/6VRB5K4qBsZpkQ3NG/VUIcNdeqZXIeHnmVi25Tu1y3x367ASjTmo3kh3Y
  NuGetKey:
    secure: zwdA2O//k/Ymxs1GPmmv+jIHlInSYJ4+kvYGyP84QLrCXD/X+Kj4WDuX9N7wetrc
  COVERALLS_REPO_TOKEN:
    secure: pmewtxEuv8kMwIMIpzrxUgLtEK8DEf90Iu96AiDjXwMObZAaI7ZTByXRZRp5dYYJ
  JAVA_HOME: C:\Program Files\Java\jdk15

build_script:
  - ps: .\build.ps1 appveyor

for:
  -
    matrix:
      except:
        - image: Visual Studio 2019
    build_script:
      - sh: ./build.sh

test: off
deploy: off